## Feature Construction Techniques

This section demonstrates various feature construction techniques:
1.  **Dummy Coding** for nominal categorical variables.
2.  **Ordinal Encoding** for ordinal categorical variables.
3.  **Transforming numeric (continuous) features** to categorical features.

In [1]:
import pandas as pd
import numpy as np

# Create sample data for demonstration
data = {
    'ID': range(1, 11),
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue', 'Green', 'Red', 'Blue', 'Green', 'Red'],
    'Size': ['Small', 'Medium', 'Large', 'Small', 'Medium', 'Small', 'Large', 'Medium', 'Small', 'Large'],
    'Age': [25, 30, 45, 22, 38, 50, 28, 35, 42, 55],
    'City': ['NY', 'LA', 'Chi', 'NY', 'LA', 'Chi', 'NY', 'LA', 'Chi', 'NY'] # Another nominal for dummy coding
}
df = pd.DataFrame(data)

print("Original DataFrame:")
display(df.head())

Original DataFrame:

   ID  Color    Size  Age City
0   1    Red   Small   25   NY
1   2   Blue  Medium   30   LA
2   3  Green   Large   45  Chi
3   4    Red   Small   22   NY
4   5   Blue  Medium   38   LA

### 1. Dummy Coding Nominal Categorical Variables

Dummy coding converts categorical variables into a numerical format that can be used by machine learning algorithms. For each unique category, a new binary column (0 or 1) is created. This is often used for nominal variables where there is no inherent order.

We will apply dummy coding to the 'Color' and 'City' columns.

In [2]:
# Perform dummy coding on 'Color' and 'City' columns
df_encoded_nominal = pd.get_dummies(df, columns=['Color', 'City'], prefix=['Color', 'City'])

print("DataFrame after Dummy Coding (Nominal Variables):")
display(df_encoded_nominal.head())

DataFrame after Dummy Coding (Nominal Variables):

,ID,Size,Age,Color_Blue,Color_Green,Color_Red,City_Chi,City_LA,City_NY
0,1,Small,25,False,False,True,False,False,True
1,2,Medium,30,True,False,False,False,True,False
2,3,Large,45,False,True,False,True,False,False
3,4,Small,22,False,False,True,False,False,True
4,5,Medium,38,True,False,False,False,True,False

### 2. Encoding Ordinal Categorical Variables

Ordinal encoding is used for categorical variables that have an intrinsic order or ranking. Each category is assigned an integer value based on its order.

We will encode the 'Size' column, which has an order: 'Small' < 'Medium' < 'Large'.

In [3]:
# Define the order for the 'Size' variable
size_order = ['Small', 'Medium', 'Large']

# Create a mapping dictionary
size_mapping = {size: i for i, size in enumerate(size_order)}

# Apply the ordinal encoding to the 'Size' column
df_encoded_nominal['Size_Encoded'] = df_encoded_nominal['Size'].map(size_mapping)

print("DataFrame after Ordinal Encoding (Ordinal Variables):")
display(df_encoded_nominal.head())

# Drop the original 'Size' column if no longer needed
df_final = df_encoded_nominal.drop(columns=['Size'])
print("DataFrame after dropping original 'Size' column:")
display(df_final.head())

DataFrame after Ordinal Encoding (Ordinal Variables):

,ID,Size,Age,Color_Blue,Color_Green,Color_Red,City_Chi,City_LA,City_NY,Size_Encoded
0,1,Small,25,False,False,True,False,False,True,0
1,2,Medium,30,True,False,False,False,True,False,1
2,3,Large,45,False,True,False,True,False,False,2
3,4,Small,22,False,False,True,False,False,True,0
4,5,Medium,38,True,False,False,False,True,False,1

DataFrame after dropping original 'Size' column:

,ID,Age,Color_Blue,Color_Green,Color_Red,City_Chi,City_LA,City_NY,Size_Encoded
0,1,25,False,False,True,False,False,True,0
1,2,30,True,False,False,False,True,False,1
2,3,45,False,True,False,True,False,False,2
3,4,22,False,False,True,False,False,True,0
4,5,38,True,False,False,False,True,False,1

### 3. Transforming Numeric (Continuous) Features to Categorical Features

This technique, often called **binning** or **discretization**, converts continuous numerical data into discrete categories (bins). This can be useful for reducing noise, handling non-linear relationships, or preparing data for models that prefer categorical inputs.

We will transform the 'Age' column into age groups (e.g., 'Young', 'Middle-aged', 'Senior').

In [4]:
# Define bin edges and labels for 'Age'
# For example, ages 0-29 as 'Young', 30-49 as 'Middle-aged', 50+ as 'Senior'
bins = [0, 29, 49, np.inf]
labels = ['Young', 'Middle-aged', 'Senior']

# Use pd.cut to create new categorical 'Age_Group' feature
df_final['Age_Group'] = pd.cut(df_final['Age'], bins=bins, labels=labels, right=True)

print("DataFrame after Transforming Numeric 'Age' to Categorical 'Age_Group':")
display(df_final.head())

# You can also apply dummy coding to the new 'Age_Group' if desired for certain models
df_final_with_age_dummies = pd.get_dummies(df_final, columns=['Age_Group'], prefix='Age')
print("DataFrame after Dummy Coding 'Age_Group':")
display(df_final_with_age_dummies.head())

DataFrame after Transforming Numeric 'Age' to Categorical 'Age_Group':

,ID,Age,Color_Blue,Color_Green,Color_Red,City_Chi,City_LA,City_NY,Size_Encoded,Age_Group
0,1,25,False,False,True,False,False,True,0,Young
1,2,30,True,False,False,False,True,False,1,Middle-aged
2,3,45,False,True,False,True,False,False,2,Middle-aged
3,4,22,False,False,True,False,False,True,0,Young
4,5,38,True,False,False,False,True,False,1,Middle-aged

DataFrame after Dummy Coding 'Age_Group':

,ID,Age,Color_Blue,Color_Green,Color_Red,City_Chi,City_LA,City_NY,Size_Encoded,Age_Young,Age_Middle-aged,Age_Senior
0,1,25,False,False,True,False,False,True,0,True,False,False
1,2,30,True,False,False,False,True,False,1,False,True,False
2,3,45,False,True,False,True,False,False,2,False,True,False
3,4,22,False,False,True,False,False,True,0,True,False,False
4,5,38,True,False,False,False,True,False,1,False,True,False